- hosts: all
  remote_user: jjohanan
  become: true
  vars_files:
    - vars.yml
  roles:
    - { role: swap, tags: [] }
    - { role: docker, tags: [] }
    - { role: service_build, service: mysql, tags: [], exec_files: ['backup.sh', 'load_db.sh'] }
    - { role: service_build, service: php, tags: [], exec_files: [] }
    - { role: service_build, service: backend, tags: ['backend'], exec_files: ['site-normal', 'site-upgrade', 'site-upgrade', 'start-nginx.sh'] }
    - { role: service_build, service: varnish, tags: ['backend'], exec_files: ['start-varnish.sh'] }
    - { role: service_build, service: frontnginx, tags: ['web'], exec_files: ['start-nginx.sh'] }
    - { role: blog_site, tags: [] }

  tasks:
    - { include: tasks/docker-compose_rebuild.yml, vars: {service: frontnginx}, tags: ['web'] }
    - { include: tasks/docker-compose_rebuild.yml, vars: {service: cadvisor}, tags: ['web'] }
    - { include: tasks/docker-compose_rebuild.yml, vars: {service: varnish}, tags: ['backend'] }
    - { include: tasks/docker-compose_rebuild.yml, vars: {service: backend}, tags: ['backend'] }
    - { include: tasks/docker-compose_rebuild.yml, vars: {service: php}, tags: [] }
    - { include: tasks/docker-compose_rebuild.yml, vars: {service: mysql}, tags: [] }

    - name: bring it all up
      command: chdir={{ work_dir }} docker-compose up -d --no-recreate
      tags:
        - web
    - name: make sure mysql comes up
      pause: seconds=15
    - name: Load blog backup database
      command: docker exec blog_mysql_1 /load_db.sh
    #- include: tasks/docker_clean.yml
